return {
  {
    'nvim-neo-tree/neo-tree.nvim',
    branch = 'v3.x',
    dependencies = {
      'nvim-lua/plenary.nvim',
      'nvim-tree/nvim-web-devicons',
      'MunifTanjim/nui.nvim',
    },
    keys = {
      { '<leader>e', '<cmd>Neotree toggle<CR>', desc = 'Toggle Neo-tree' },
    },
    opts = {
      default_component_configs = {
        icon = {
          folder_closed = '▸',
          folder_open = '▾',
          folder_empty = '□',
          folder_empty_open = '◇',
          default = '*',
          provider = function(icon, node, state)
            if node.type ~= 'file' then return end
            local default = '·'
            local ext_icons = {
              md = '§',
              sh = '>',
              json = '{ }',
              lua = '◇',
              go = '◎',
              py = '▶',
              js = '◈',
              ts = '◈',
              rs = '◇',
              rb = '◆',
              ex = '◆',
              yaml = '≡',
              toml = '≡',
              txt = '·',
              cfg = '·',
              conf = '·',
              ini = '·',
              gz = '⎔',
              zip = '⎔',
              tar = '⎔',
              rar = '⎔',
              bz2 = '⎔',
              xz = '⎔',
              ['7z'] = '⎔',
              iso = '⎔',
              gitignore = '○',
              dockerignore = '○',
              lock = '◎',
              log = '¶',
              err = '×',
              out = '×',
              pdf = '□',
              png = '▣',
              jpg = '▣',
              jpeg = '▣',
              gif = '▣',
              svg = '▣',
              ico = '▣',
              css = '#',
              scss = '#',
              less = '#',
              html = '<>',
              htm = '<>',
              xml = '<>',
              sql = '⎈',
              db = '⎈',
              c = '◎',
              cpp = '◎',
              h = '◎',
              hpp = '◎',
              java = '◎',
              kt = '◎',
              swift = '◎',
              dart = '◎',
            }
            local ext = vim.fn.fnamemodify(node.name, ':e'):lower()
            icon.text = ext_icons[ext] or default
            icon.highlight = 'NeoTreeFileIcon'
          end,
        },
      },
      filesystem = { follow_current_file = { enabled = true } },
    },
  },
}