local has_ripgrep = vim.fn.executable('rg') == 1

local vimgrep_arguments
if has_ripgrep then
  vimgrep_arguments = {
    'rg',
    '--color=never',
    '--no-heading',
    '--with-filename',
    '--line-number',
    '--column',
    '--smart-case',
  }
else
  vimgrep_arguments = {
    'grep',
    '--color=never',
    '--recursive',
    '--line-number',
  }
end

return {
  {
    'nvim-telescope/telescope.nvim',
    tag = 'v0.2.2',
    dependencies = { 'nvim-lua/plenary.nvim' },
    config = function()
      require('telescope').setup({
        defaults = {
          vimgrep_arguments = vimgrep_arguments,
          prompt_prefix = '>',
          selection_caret = '>',
          path_display = { 'truncate' },
          layout_strategy = 'flex',
          layout_config = {
            width = 0.99,
            height = 0.9,
            horizontal = { preview_cutoff = 55, prompt_position = 'bottom' },
            vertical = { preview_cutoff = 55, prompt_position = 'bottom' },
          },
file_ignore_patterns = {
  '%.git/',
  'node_modules',
  '%.venv/',
  '__pycache__',
  '%.mypy_cache/',
  '%.pytest_cache/',
  '%.cache/',
  '%.docker/',
  '%.terraform/',
  '%.aws/',
  'kube/',
  '%.sqlite',
  '%.db',
  '%.duckdb',
  'data/db/',
  'supabase/',
  '%.astro/',
  '%.remix/',
  '%.turbo/',
  '%.vercel/',
  '%.netlify/',
  'bin/',
  'obj/',
  '%.gopls/',
  'dist-newstyle/',
  '%.stack-work/',
  '%.docusaurus/',
  'site/',
  '_site/',
  '%.vitepress/dist/',
  '%.wrangler/',
  '%.dev/',
  '%.cloudflare/',
  '%.next/',
  '%.nuxt/',
  '%.output/',
  'dist/',
  'build/',
  'out/',
  '%.nitro/',
  '%.content-cache/',
  '%.mp4',
  '%.mov',
  '%.avi',
  '%.png',
  '%.jpg',
  '%.jpeg',
  '%.webp',
  '%.gif',
  '%.mp3',
  '%.wav',
  '%.flac',
  '%.zip',
  '%.tar%.gz',
  '%.rar',
  '%.7z',
},          mappings = {
            i = {
              ['<C-j>'] = 'move_selection_next',
              ['<C-k>'] = 'move_selection_previous',
            },
            n = {
              ['<C-j>'] = 'move_selection_next',
              ['<C-k>'] = 'move_selection_previous',
            },
          },
        },
      })
    end,
    keys = {
      -- VSCode-style Ctrl+P quick-open + Ctrl+Shift+P command  palette.
      -- <leader>1/ff/fo remain as fallbacks (some terminals send <C-p> for <C-S-p>).
      { '<C-p>',        '<cmd>Telescope find_files<CR>',                desc = 'Find files (Ctrl+P)' },
      { '<leader>p',        '<cmd>Telescope find_files<CR>',                desc = 'Find files (Leader+p)' },
      { '<C-S-p>',      '<cmd>Telescope commands<CR>',                 desc = 'Commands (Ctrl+Shift+P)' },
      { '<leader>P',      '<cmd>Telescope commands<CR>',                 desc = 'Commands (Leader+P)' },
      { '<leader>1',      '<cmd>Telescope find_files<CR>',                desc = 'Find files' },
      { '<leader>ff',   '<cmd>Telescope find_files hidden=true<CR>',    desc = 'Find files (hidden)' },
      { '<leader>fg',   '<cmd>Telescope live_grep<CR>',                 desc = 'Live grep' },
      { '<leader>fG',   '<cmd>Telescope grep_cword<CR>',                desc = 'Grep word under cursor' },
      { '<leader>f;',   '<cmd>Telescope grep_last_word<CR>',            desc = 'Grep last searched word' },
      { '<leader>fz',   '<cmd>Telescope current_buffer_fuzzy_find<CR>', desc = 'Fuzzy find in buffer' },
      { '<leader>fb',   '<cmd>Telescope buffers<CR>',                   desc = 'Buffers' },
      { '<leader>fh',   '<cmd>Telescope help_tags<CR>',                  desc = 'Help tags' },
      { '<leader>fr',   '<cmd>Telescope oldfiles<CR>',                  desc = 'Recent files' },
      { '<leader>fo',   '<cmd>Telescope commands<CR>',                  desc = 'Commands' },
      { '<leader>fR',   '<cmd>Telescope resume<CR>',                    desc = 'Resume last search' },
      { '<leader>gs',   '<cmd>Telescope git_status<CR>',                desc = 'Git status' },
      { '<leader>gb',   '<cmd>Telescope git_branches<CR>',              desc = 'Git branches' },
      { '<leader>gc',   '<cmd>Telescope git_commits<CR>',               desc = 'Git commits' },
      { '<leader>gC',   '<cmd>Telescope git_bcommits<CR>',              desc = 'Git buffer commits' },
    },
  },
}
